# Generated by Django 3.1.5 on 2021-02-01 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_snack'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='snacks',
            field=models.ManyToManyField(to='main_app.Snack'),
        ),
    ]
