# Generated by Django 3.1.5 on 2021-02-01 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_movie_snacks'),
    ]

    operations = [
        migrations.AddField(
            model_name='snack',
            name='name',
            field=models.CharField(default='Sour Patch Kids', max_length=50),
        ),
    ]
